### PR TITLE
Add types

### PR DESCRIPTION
**Pull request by frankyjuang**
# Summary

https://github.com/react-native-community/react-native-cookies/issues/8

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅❌     |
| Android |    ✅❌     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added the documentation in `README.md`
- [ ] I mentioned this change in `CHANGELOG.md`
- [ ] I updated the typed files (TS and Flow)
- [ ] I added a sample use of the API in the example project (`example/App.js`)

### CODE REVIEW

**Comment by frankyjuang** [comment]
@safaiyeh the return types of android and ios are not aligned. Sometimes it's boolean in android but undefined in ios. Same for with and without `useWebKit`

**Comment by safaiyeh** [comment]
Thanks for this @frankyjuang! Let's make an issue for the inconsistent returns and fix that in another PR.

**Comment by safaiyeh** [comment]
This looks good, could you add types field to `package.json` and I'll merge this in. ref: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package

**Comment by frankyjuang** [comment]
Added. Thanks.

**Pull request merged**
